blank_issues_enabled: false
contact_links:
  - name: Installation/Launcher/Miscellaneous Issues
    url: https://discord.gg/wq4dtE3kBh
    about: If you one of the above issues or any other concern(s) or question(s), you can reach out to us on our Discord!
